
export const FETCH_LOGIN_REQUEST = 'relax-user/FETCH_LOGIN_REQUEST'
export const FETCH_LOGIN_SUCCESS = 'relax-user/FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_FAILURE = 'relax-user/FETCH_LOGIN_FAILURE'

export const FETCH_SIGNUP_REQUEST = 'relax-user/FETCH_SIGNUP_REQUEST'
export const FETCH_SIGNUP_SUCCESS = 'relax-user/FETCH_SIGNUP_SUCCESS'
export const FETCH_SIGNUP_FAILURE = 'relax-user/FETCH_SIGNUP_FAILURE'

export const FETCH_LOGOUT_REQUEST = 'relax-user/FETCH_LOGOUT_REQUEST'
export const FETCH_LOGOUT_SUCCESS = 'relax-user/FETCH_LOGOUT_SUCCESS'
export const FETCH_LOGOUT_FAILURE = 'relax-user/FETCH_LOGOUT_FAILURE'